local CURRENT_MODULE_NAME = (...)
require("config")
require("cocos.init")
require("framework.init")
require("DataEye.init")
require("dygame.init")

local function doInit()
  cc.FileUtils:getInstance():purgeCachedEntries()
  local appName = string.sub(CURRENT_MODULE_NAME, 1, -6)
  local hotfixPath = DYUtils.hotfixPath()
  cc.FileUtils:getInstance():addSearchPath(hotfixPath .. "res/")
  cc.FileUtils:getInstance():addSearchPath(hotfixPath .. "res/" .. appName)
  cc.FileUtils:getInstance():addSearchPath(hotfixPath .. "res/uikit")
  cc.FileUtils:getInstance():addSearchPath(hotfixPath .. "src/")
  cc.FileUtils:getInstance():addSearchPath(hotfixPath .. "src/" .. appName)
  cc.FileUtils:getInstance():addSearchPath("res/")
  cc.FileUtils:getInstance():addSearchPath("res/" .. appName)
  cc.FileUtils:getInstance():addSearchPath("res/uikit")
  cc.FileUtils:getInstance():addSearchPath("src/")
  cc.FileUtils:getInstance():addSearchPath("src/" .. appName)
  DYLang.loadDefault("app.locale.cn")
end

doInit()
