local CSVParser = require("app.utils.CSVParser")
local M = {}
M.BUDDHA_INFO = require("app.profiles.buddha")
M.BUDDHA_MODEL_INFO = require("app.profiles.buddha_model")
M.CIMELIA_INFO = require("app.profiles.cimelia")
M.CIMELIA_SKILL_INFO = require("app.profiles.cimelia_skill")
M.CIMELIA_EXP_INFO = require("app.profiles.cimelia_exp")
M.CIMELIA_QUALITY_INFO = require("app.profiles.cimelia_quality")
M.CIMELIA_RECAST_COST = require("app.profiles.cimelia_recast")
M.CIMELIA_GRADE_UP = require("app.profiles.cimelia_gradeup")
M.CIMELIA_PROP_INFO = require("app.profiles.cimelia_props")
M.BUDDHA_SKILL_INFO = require("app.profiles.buddha_skill")
M.BUDDHA_AWAKE_INFO = require("app.profiles.buddha_arousal")
M.BUDDHA_FATE_INFO = require("app.profiles.fate")
M.NEW_GUIDE_INFO = require("app.profiles.newguide")
M.BREAK_BASE_INFO = require("app.profiles.break_base")
M.BREAK_ADD_INFO = require("app.profiles.break_add")
M.GAME_ITEM_INFO = require("app.profiles.game_item")
M.USER_NAME_INFO = require("app.profiles.username")
M.MONSTER_INFO = require("app.profiles.monster")
M.SPIRIT_INFO = require("app.profiles.spirit")
M.PVP_SPIRIT_INFO = require("app.profiles.spirit_pvp")
M.PVP_COUNT_CONSUME = require("app.profiles.countConsume")
M.TEAM_GRID_INFO = require("app.profiles.team_grid")
M.CONST = require("app.profiles.const")
M.NEW_GUIDE_INFO = import("app.profiles.newguide")
M.VIP_PRIVILEGE_INFO = require("app.profiles.vip")
M.PAYMENT_INFO = require("app.profiles.payment")
M.PLAYER_EXP_LEVEL_INFO = require("app.profiles.player_exp")
M.MAIN_CHAPTER_INFO = require("app.profiles.chapter")
M.CHAPTER_LOCATION_INFO = require("app.profiles.chapter_location")
M.ELITE_CHAPTER_INFO = require("app.profiles.chapter_h")
M.ELITE_LOCATION_INFO = require("app.profiles.elite_location")
M.STAGE_INFO = require("app.profiles.stage")
M.INFINITE_STAGE_INFO = require("app.profiles.stage_infinite")
M.PURGATORY_STAGE_INFO = require("app.profiles.stage_purgatory")
M.TRAVEL_STAGE_INFO = require("app.profiles.stage_travel")
M.TOWER_STAGE_INFO = require("app.profiles.stage_babel")
M.AGGRESS_STAGE_INFO = require("app.profiles.stage_aggress")
M.AI_INFO = require("app.profiles.AI")
M.STRATEGY_INFO = require("app.profiles.strategy")
M.INFINITE_AI = require("app.profiles.AI_infinite")
M.INFINITE_STRATEGY = require("app.profiles.strategy_infinite")
M.STOVE_INFO = require("app.profiles.stove")
M.ACTIVITY_INFO = require("app.profiles.activity")
M.ACTIVITY_TASK1 = require("app.profiles.activityTask1")
M.ACTIVITY_TASK2 = require("app.profiles.activityTask2")
M.ACTIVITY_TASK3 = require("app.profiles.activityTask3")
M.ACTIVITY_SEVEN = require("app.profiles.sevenActivity")
M.SEVEN_TASK = require("app.profiles.sevenTask")
M.TREASURE_INFO = require("app.profiles.treasure")
M.TREASURE_PIECE_INFO = require("app.profiles.treasure_piece")
M.ACHIEVEMENT_INFO = require("app.profiles.achievement")
M.DAILYTASK_INFO = require("app.profiles.task_daily")
M.TASK_BOX_INFO = require("app.profiles.task_box")
M.LEVEL_UP_TIPS = require("app.profiles.levelUpTips")
M.DIALOGUE_INFO = require("app.profiles.dialogue")
M.TEAM_STAR_INFO = require("app.profiles.team_starfate")
M.PVP_OL_ACTUAL_INFO = require("app.profiles.pvp_actual")
M.NIAN_ACTUAL_INFO = require("app.profiles.nianrank")
M.NIAN_HURT_INFO = require("app.profiles.nianhurt")
M.PVP_OL_FIGHT_AWARD = require("app.profiles.pvp_fightaward")
M.SHIELDING_WORDS = require("app.profiles.shielding_words")
M.PURGATORY_BOX = require("app.profiles.purgatory_box")
M.UNION_CONTRI_BOX = require("app.profiles.union_construct_prize")
M.UNION_BATTLE_AWARD = require("app.profiles.union_war_s")
M.ACTION = require("app.profiles.action")
M.ACTION_SERIES = require("app.profiles.actionSeries")
M.STRATEGY = require("app.profiles.aiStrategy")
M.EQUIPMENT_INFO = require("app.profiles.equipment")
M.EQUIPMENT_EXP_INFO = require("app.profiles.equipment_upgrade")
M.EQUIPMENT_UPSTAR_COST = require("app.profiles.equipment_star")
M.EQUIPMENT_PROP_INFO = require("app.profiles.equipment_props")
M.EQUIPMENT_SUIT_INFO = require("app.profiles.equipment_suit")
M.RELICS_SKILL_INFO = require("app.profiles.relics_skill")
M.PATROL = require("app.profiles.patrol")
M.PATROL_GOAL = require("app.profiles.patrol_goal")
local str = require("app.profiles.goods_info")
M.GOODS_INFO = CSVParser.new(str, true)
local str = require("app.profiles.spirit_cost_basic")
M.SPIRIT_COST_BASIC_INFO = CSVParser.new(str, true)
local str = require("app.profiles.fortune_wheel")
M.FORTUNE_WHEEL_INFO = CSVParser.new(str, true)

local function mergeEquipmentToGameItem()
  for i = 2, #M.EQUIPMENT_INFO do
    local value = M.EQUIPMENT_INFO[i]
    table.insert(M.GAME_ITEM_INFO, value)
  end
end

mergeEquipmentToGameItem()
DDLOG("load profiles done.....")
return M
