DEBUG = 0
DEBUG_FPS = false
DEBUG_MEM = false
DEBUG_PROFILE = false
LOAD_DEPRECATED_API = false
LOAD_SHORTCODES_API = true
CONFIG_SCREEN_ORIENTATION = "landscape"
CONFIG_SCREEN_WIDTH = 1280
CONFIG_SCREEN_HEIGHT = 720
CONFIG_SCREEN_AUTOSCALE = "FIXED_HEIGHT"
CONFIG_GAME = {
  id = 2001,
  ver = "1.3.1.160323",
  mode = "release",
  logToFile = false
}
