#!/usr/bin/ruby -w
# encoding:  UTF-8
require 'rexml/document'
include REXML

CREATE_SIGN=
    '-----------------------------------------------------------------
-- GENERATED BY TOOLS, NO NOT MODIFY IT.
-----------------------------------------------------------------

'

PROTOCOL_OBJ_DEFINE =
    '-----------------------------------------------------------------
-- protocol object

'

PROTOCOL_OBJ_REGISTER =
    '-----------------------------------------------------------------
-- protocol object register
'

#parse dto
def parseFile path
  file = File.new(path)
  outfile = File.new('DTO.lua', 'w+')

  _doc = Document.new file

  # outfile.puts CREATE_SIGN
  # outfile.puts PROTOCOL_OBJ_DEFINE
  _doc.root.elements.each do |element|
    #dto object
    if element.name=='dto' then
      parseDTO(element, outfile)
    end
  end

  outfile.puts PROTOCOL_OBJ_REGISTER
  _doc.root.elements.each do |element|
    #protocol
    if element.name=='protocol' then
      protocolName = element.attributes['name']
      dtoName= element.attributes['dto']
      outfile.puts "DataLayer.CACHE[Protocol.#{protocolName}] = #{dtoName}"
    end
  end

  outfile.flush
  outfile.close

end

FUNC_DEFINE_BEGIN_STR =
    'PROTO_NAME = {}
PROTO_NAME = class("PROTO_NAME")
PROTO_NAME.__index = PROTO_NAME

ATTRIBUTES
function PROTO_NAME:ctor(ver)
    ver = ver or 1
'

FUNC_END_STR_0 =
    'end
'

FUNC_END_STR =
    'end
'


FUNC_DECODE_BEGIN_STR = '
function PROTO_NAME:decode(buf,ver)
'

FUNC_ENCODE_BEGIN_STR = '
function PROTO_NAME:encode(buf,ver)
'

DECODE_ARRAY_STR =
    '    local len = buf:readShort()
    for i=1, len, 1 do
        local data = PROTO_NAME.new(ver)
        data:decode(buf,ver)
        self.NAME[i] = data
    end
'

DECODE_ARRAY_STR_VER =
    '        local len = buf:readShort()
        for i=1, len, 1 do
            local data = PROTO_NAME.new(ver)
            data:decode(buf,ver)
            self.NAME[i] = data
        end
'

ENCODE_ARRAY_STR =
    '    local len = #self.NAME
    buf:writeShort(len)
    for i=1,len,1 do
        self.NAME[i]:encode(buf,ver)
    end
'

ENCODE_ARRAY_STR_VER =
    '        local len = #self.NAME
        buf:writeShort(len)
        for i=1,len,1 do
            self.NAME[i]:encode(buf,ver)
        end
'

ENCODE_ARRAY_STR2 =
    '    local len = #self.NAME
    buf:writeShort(len)
    for i=1,len,1 do
    DATA(self.NAME[i])
    end
'

ENCODE_ARRAY_STR2_VER =
    '        local len = #self.NAME
        buf:writeShort(len)
        for i=1,len,1 do
        DATA(self.NAME[i])
        end
'

DECODE_ARRAY_STR2 =
    '    local len = buf:readShort()
    for i=1, len, 1 do
        self.NAME[i] = DATA
    end
'

DECODE_ARRAY_STR2_VER =
    '        local len = buf:readShort()
        for i=1, len, 1 do
            self.NAME[i] = DATA
        end
'

DESC_STR =
    '-- DESC'

#parse item
def parseDTO(element, outfile)

  #define
  protoName = element.attributes['name']
  # desc = element.attributes['desc']
  # if desc!=nil
  #   str = DESC_STR.gsub(/DESC/, desc)
  #   outfile.puts str
  # end


  attributes = ''
  element.elements.each do |subElement|
    if subElement.name == 'item'
      propName = subElement.attributes['name']
      attribute = "#{protoName}.#{propName} = nil\n"
      attributes += attribute
    end
  end
  begineStr=FUNC_DEFINE_BEGIN_STR.gsub(/PROTO_NAME/, protoName)
  begineStr = begineStr.gsub(/ATTRIBUTES/, attributes)
  outfile.write(begineStr)

  element.elements.each do |subElement|
    if subElement.name == 'item'
      defineItem(subElement, outfile)
    end
  end
  outfile.write(FUNC_END_STR_0)

  #Decode
  begineStr=FUNC_DECODE_BEGIN_STR.gsub(/PROTO_NAME/, protoName)
  outfile.write(begineStr)
  element.elements.each do |subElement|
    if subElement.name == 'item'
      decodeItem(subElement, outfile)
    end
  end
  outfile.write(FUNC_END_STR)

  #Encode
  begineStr=FUNC_ENCODE_BEGIN_STR.gsub(/PROTO_NAME/, protoName)
  outfile.write(begineStr)
  element.elements.each do |subElement|
    if subElement.name == 'item'
      encodeItem(subElement, outfile)
    end
  end
  outfile.write(FUNC_END_STR)
  outfile.puts ''

end

def defineItem(element, outfile)
  propName = element.attributes['name']
  typeName = element.attributes['type']
  isArray = element.attributes['isArray']=='true'
  desc = element.attributes['desc']
  ver = element.attributes['ver']

  # if(ver)
  #   puts ver
  # end

  if desc!=nil
    if isArray
      if(ver)
        outfile.puts("    if(ver >= #{ver}) then self.#{propName} = " + getDefault(typeName, isArray) + ' end -- 【' + typeName +'】' + desc)
      else
        outfile.puts("    self.#{propName} = " + getDefault(typeName, isArray) + ' -- 【' + typeName +'】' + desc)
      end
    else
      if(ver)
        outfile.puts("    if(ver >= #{ver}) then self.#{propName} = " + getDefault(typeName, isArray) + ' end -- ' + desc)
      else
        outfile.puts("    self.#{propName} = " + getDefault(typeName, isArray) + ' -- ' + desc)
      end
    end
  else
    if isArray
      if(ver)
        outfile.puts("    if(ver >= #{ver}) then self.#{propName} = " + getDefault(typeName, isArray) + ' end -- 【' + typeName +'】')
      else
        outfile.puts("    self.#{propName} = " + getDefault(typeName, isArray) + ' -- 【' + typeName +'】')
      end
    else
      if(ver)
        outfile.puts("    if(ver >= #{ver}) then self.#{propName} = " + getDefault(typeName, isArray) + ' end')
      else
        outfile.puts("    self.#{propName} = " + getDefault(typeName, isArray))
      end
    end
  end

end

def getDefault(type, isArray)
  if (isArray) then
    return '{}'
  end

  if type=='string'
    return '""'
  elsif type=='int'
    return '0'
  elsif type=='byte'
    return '0'
  elsif type=='ubyte'
    return '0'
  elsif type=='short'
    return '0'
  elsif type=='ushort'
    return '0'
  elsif type=='uint'
    return '0'
  elsif type=='float'
    return '0.0'
  elsif type=='double'
    return '0.0'
  end

  return type+'.new(ver)'

end

def decodeItem(element, outfile)
  propName = element.attributes['name']
  typeName = element.attributes['type']
  isArray = element.attributes['isArray']=='true'
  ver = element.attributes['ver']

  if isArray
    if isUserType(typeName)
      if(ver)
        str = DECODE_ARRAY_STR_VER.gsub(/PROTO_NAME/, typeName)
      else
        str = DECODE_ARRAY_STR.gsub(/PROTO_NAME/, typeName)
      end
      str = str.gsub(/NAME/, propName)

      if(ver)
        outfile.puts "    if(ver >= #{ver}) then"
        outfile.puts str
        outfile.puts '    end'
      else
        outfile.puts str
      end
    else
      _str = getDecodeName(typeName)
      if(ver)
        str = DECODE_ARRAY_STR2_VER.gsub(/PROTO_NAME/, typeName)
      else
        str = DECODE_ARRAY_STR2.gsub(/PROTO_NAME/, typeName)
      end
      str = str.gsub(/NAME/, propName)
      str = str.gsub(/DATA/, _str)
      if(ver)
        outfile.puts "    if(ver >= #{ver}) then"
        outfile.puts str
        outfile.puts '    end'
      else
        outfile.puts str
      end
    end

  else
    _str = getDecodeName(typeName)

    if _str
      if(ver)
        outfile.puts("    if(ver >= #{ver}) then self.#{propName} = "+getDecodeName(typeName) + ' end')
      else
        outfile.puts("    self.#{propName} = "+getDecodeName(typeName))
      end
    else
      if(ver)
        outfile.puts("    if(ver >= #{ver}) then self.#{propName}:decode(buf,ver) end")
      else
        outfile.puts("    self.#{propName}:decode(buf,ver) ")
      end
    end
  end

end

def encodeItem(element, outfile)
  propName = element.attributes['name']
  typeName = element.attributes['type']
  isArray = element.attributes['isArray']=='true'
  ver = element.attributes['ver']

  if isArray
    if isUserType(typeName)
      if(ver)
        str = ENCODE_ARRAY_STR_VER.gsub(/NAME/, propName)
        outfile.puts "    if(ver >= #{ver}) then"
        outfile.puts str
        outfile.puts '    end'
      else
        str = ENCODE_ARRAY_STR.gsub(/NAME/, propName)
        outfile.puts str
      end
    else
      _str = getEncodeName2(typeName)
      if(ver)
        str = ENCODE_ARRAY_STR2_VER.gsub(/NAME/, propName)
      else
        str = ENCODE_ARRAY_STR2.gsub(/NAME/, propName)
      end
      str = str.gsub(/DATA/, _str)

      if(ver)
        outfile.puts "    if(ver >= #{ver}) then"
        outfile.puts str
        outfile.puts '    end'
      else
        outfile.puts str
      end
    end

  else
    str = getEncodeName(typeName)
    str = str.gsub(/NAME/, propName)
    if(ver)
      str = "    if(ver >= #{ver}) then "+str+' end'
    end
    outfile.puts(str)
  end
end

def getDecodeName(type)
  if type=='string'
    return 'buf:readStringUShort()'
  elsif type=='int'
    return 'buf:readInt()'
  elsif type=='byte'
    return 'buf:readChar()'
  elsif type=='ubyte'
    return 'buf:readByte()'
  elsif type=='short'
    return 'buf:readShort()'
  elsif type=='ushort'
    return 'buf:readUShort()'
  elsif type=='uint'
    return 'buf:readUInt()'
  elsif type=='float'
    return 'buf:readFloat()'
  elsif type=='double'
    return 'buf:readDouble()'
  end
end

def getEncodeName(type)
  if type=='string'
    return '    buf:writeStringUShort(self.NAME)'
  elsif type=='int'
    return '    buf:writeInt(self.NAME)'
  elsif type=='byte'
    return '    buf:writeChar(self.NAME)'
  elsif type=='ubyte'
    return '    buf:writeByte(self.NAME)'
  elsif type=='short'
    return '    buf:writeShort(self.NAME)'
  elsif type=='ushort'
    return '    buf:writeUShort(self.NAME)'
  elsif type=='uint'
    return '    buf:writeUInt(self.NAME)'
  elsif type=='float'
    return '    buf:writeFloat(self.NAME)'
  elsif type=='double'
    return '    buf:writeDouble(self.NAME)'
  end

  return '    self.NAME:encode(buf,ver)'
end

def getEncodeName2(type)
  if type=='string'
    return '    buf:writeStringUShort'
  elsif type=='int'
    return '    buf:writeInt'
  elsif type=='byte'
    return '    buf:writeChar'
  elsif type=='ubyte'
    return '    buf:writeByte'
  elsif type=='short'
    return '    buf:writeShort'
  elsif type=='ushort'
    return '    buf:writeUShort'
  elsif type=='uint'
    return '    buf:writeUInt'
  elsif type=='float'
    return '    buf:writeFloat'
  elsif type=='double'
    return '    buf:writeDouble'
  end

  return ''
end

def isUserType(type)
  if type=='string'
    return false
  elsif type=='int'
    return false
  elsif type=='byte'
    return false
  elsif type=='ubyte'
    return false
  elsif type=='short'
    return false
  elsif type=='ushort'
    return false
  elsif type=='uint'
    return false
  elsif type=='float'
    return false
  elsif type=='double'
    return false
  end

  return true
end

parseFile('dto.xml')



